/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: cb54d0a1a3ed7065d848475266ea83e4)
interface __BaseEnv_Env {
	DIRECTORY: D1Database;
	ASSETS: Fetcher;
	ENVIRONMENT: "production";
	GITHUB_APP_CLIENT_ID: "replace-with-client-id";
	GITHUB_APP_SLUG: "replace-with-app-slug";
	REPO_BOARD: DurableObjectNamespace<import("./src/worker/index").RepoBoard>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker/index");
		durableNamespaces: "RepoBoard";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "GITHUB_APP_CLIENT_ID" | "GITHUB_APP_SLUG">> {}
}
