/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 639785587b56dc4103b5d6d448fd1d52)
interface __BaseEnv_Env {
	DIRECTORY: D1Database;
	ASSETS: Fetcher;
	ENVIRONMENT: "production";
	GITHUB_APP_CLIENT_ID: "Iv23lieDHBQ8Wg8zQTqt";
	GITHUB_APP_SLUG: "webmcp-repo-board";
	GITHUB_APP_ID: string;
	GITHUB_APP_PRIVATE_KEY: string;
	GITHUB_APP_CLIENT_SECRET: string;
	GITHUB_WEBHOOK_SECRET: string;
	REPO_BOARD: DurableObjectNamespace<import("./src/worker/index").RepoBoard>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker/index");
		durableNamespaces: "RepoBoard";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "GITHUB_APP_CLIENT_ID" | "GITHUB_APP_SLUG" | "GITHUB_APP_ID" | "GITHUB_APP_PRIVATE_KEY" | "GITHUB_APP_CLIENT_SECRET" | "GITHUB_WEBHOOK_SECRET">> {}
}
